Feature/11 register log in account
Big-Cow-King/PlayPal-Frontend pull request #25
Opened 2024-02-08 19:40 UTC by Zizizzz

This PR fixes/implements the following **bugs/features**

* [x] Feature 11

**Description**
This PR implement the create account and login feature of the application.

close #11

2024-02-08 19:42 UTC, Zizizzz reviewed
Reviewed changes

2024-02-08 20:00 UTC, jingwenshi-dev commented
Fill in the information of your PR first

2024-02-08 21:15 UTC, jingwenshi-dev requested changes
Fill in the PR description first before asking for review.

2024-02-09 03:54 UTC, jingwenshi-dev approved these changes

2024-02-09 03:54 UTC, merged